sudo : required
services:
        - docker

before_install:
        - docker build -t sachipat/react-checkpoint -f ./client/Dockerfile.dev .

script:
        docker run -e CI=true -it sachipat/react-checkpoint npm test
